-- Set Partner Timeout

ALTER DATABASE prodAFI_dw SET PARTNER TIMEOUT 90
ALTER DATABASE prodAFI2_dw SET PARTNER TIMEOUT 90
ALTER DATABASE prodCEMIC_dw SET PARTNER TIMEOUT 90
ALTER DATABASE prodCEMIC_HIST_dw SET PARTNER TIMEOUT 90
ALTER DATABASE prodCNIC_dw SET PARTNER TIMEOUT 90
ALTER DATABASE prodDMIC_dw SET PARTNER TIMEOUT 90
ALTER DATABASE prodFICOH_dp SET PARTNER TIMEOUT 90
ALTER DATABASE prodFICOH_dw SET PARTNER TIMEOUT 90
ALTER DATABASE prodFICOH_wp SET PARTNER TIMEOUT 90
ALTER DATABASE prodMMIC_dw SET PARTNER TIMEOUT 90
ALTER DATABASE prodMWUA_dw SET PARTNER TIMEOUT 90
ALTER DATABASE prodSPIA_dw SET PARTNER TIMEOUT 90
ALTER DATABASE prodSPPC_dw SET PARTNER TIMEOUT 90
ALTER DATABASE prodZAG_dw SET PARTNER TIMEOUT 90
