-- Add additional tempdb data files

ALTER DATABASE tempdb 
ADD FILE (NAME = tempdb2, FILENAME = 'F:\MSSQL\TempDB\tempdb2.ndf', SIZE = 1024MB, FILEGROWTH = 1000MB, MAXSIZE = 20480MB)
GO
ALTER DATABASE tempdb 
ADD FILE (NAME = tempdb3, FILENAME = 'F:\MSSQL\TempDB\tempdb3.ndf', SIZE = 1024MB, FILEGROWTH = 1000MB, MAXSIZE = 20480MB)
GO
ALTER DATABASE tempdb 
ADD FILE (NAME = tempdb4, FILENAME = 'F:\MSSQL\TempDB\tempdb4.ndf', SIZE = 1024MB, FILEGROWTH = 1000MB, MAXSIZE = 20480MB)
GO

-- Alter Logical Filename and default sizes
ALTER DATABASE tempdb
MODIFY FILE (NAME = 'tempdev' , NEWNAME = 'tempdb', SIZE = 1024MB, FILEGROWTH = 1000MB, MAXSIZE = 20480MB)

ALTER DATABASE tempdb
MODIFY FILE (NAME = 'templog', SIZE = 5120MB, FILEGROWTH = 1000MB, MAXSIZE = 20480MB)