
ALTER DATABASE DH_PREPROD
MODIFY FILE (NAME = 'dh_dev' , NEWNAME = 'DH_PREPROD')

ALTER DATABASE DH_PREPROD
MODIFY FILE (NAME = 'dh_dev_log' , NEWNAME = 'DH_PREPROD_log')


ALTER DATABASE IC_PREPROD
MODIFY FILE (NAME = 'ic_dev' , NEWNAME = 'IC_PREPROD')

ALTER DATABASE IC_PREPROD
MODIFY FILE (NAME = 'ic_dev_log' , NEWNAME = 'IC_PREPROD_log')