-- Set Partner Timeout

ALTER DATABASE prodAFI SET PARTNER TIMEOUT 90
ALTER DATABASE prodAFI2 SET PARTNER TIMEOUT 90
ALTER DATABASE prodCEMIC SET PARTNER TIMEOUT 90
ALTER DATABASE prodCEMIC_HIST SET PARTNER TIMEOUT 90
ALTER DATABASE prodCNIC SET PARTNER TIMEOUT 90
ALTER DATABASE prodCNIC_dp SET PARTNER TIMEOUT 90
ALTER DATABASE prodCNIC_wp SET PARTNER TIMEOUT 90
ALTER DATABASE prodDMIC SET PARTNER TIMEOUT 90
ALTER DATABASE prodDMIC_wp SET PARTNER TIMEOUT 90
ALTER DATABASE prodFICOH SET PARTNER TIMEOUT 90
ALTER DATABASE prodMMIC SET PARTNER TIMEOUT 90
ALTER DATABASE prodMMIC_dp SET PARTNER TIMEOUT 90
ALTER DATABASE prodMMIC_wp SET PARTNER TIMEOUT 90
ALTER DATABASE prodMWUA SET PARTNER TIMEOUT 90
ALTER DATABASE prodMWUA_wp SET PARTNER TIMEOUT 90
ALTER DATABASE prodSPIA SET PARTNER TIMEOUT 90
ALTER DATABASE prodSPPC SET PARTNER TIMEOUT 90
ALTER DATABASE prodSPPC_wp SET PARTNER TIMEOUT 90
ALTER DATABASE prodZAG SET PARTNER TIMEOUT 90
