--- YOU MUST EXECUTE THE FOLLOWING SCRIPT IN SQLCMD MODE.
:Connect WSFCNODE1
USE [master]
GO
ALTER AVAILABILITY GROUP [PreProd]
ADD DATABASE [$(db_name)];
GO
:Connect WSFCNODE1
BACKUP DATABASE [$(db_name)] TO  DISK = N'\\WSFCNODE1\Replica\$(db_name).bak' WITH  COPY_ONLY, FORMAT, INIT, SKIP, REWIND, NOUNLOAD, COMPRESSION,  STATS = 5
GO
:Connect WSFCNODE2
RESTORE DATABASE [$(db_name)] FROM  DISK = N'\\WSFCNODE1\Replica\$(db_name).bak' WITH  NORECOVERY,  NOUNLOAD,  STATS = 5
GO
:Connect WSFCNODE1
BACKUP LOG [$(db_name)] TO  DISK = N'\\WSFCNODE1\Replica\$(db_name).trn' WITH NOFORMAT, INIT, NOSKIP, REWIND, NOUNLOAD, COMPRESSION,  STATS = 5
GO
:Connect WSFCNODE2
RESTORE LOG [$(db_name)] FROM  DISK = N'\\WSFCNODE1\Replica\$(db_name).trn' WITH  NORECOVERY,  NOUNLOAD,  STATS = 5
GO
:Connect WSFCNODE2
ALTER DATABASE [$(db_name)] SET HADR AVAILABILITY GROUP = [PreProd];
GO
GO


